[tool.poetry]
name = "NBA"
version = "0.1.0"
description = ""
authors = ["Sravan Pannala <57152030+sravanpannala@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pbpstats = "^1.3.2"
nba-api = "^1.1.9"
jupyter-dash = "^0.4.0"
seaborn = "^0.11.2"
kaleido = "0.2.1"
ipywidgets = "^7.6.5"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
