[project]
name = "nba"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0,<3.12.0"
dependencies = [
    "dill>=0.3.9",
    "icecream>=2.1.4",
    "imageio[ffmpeg]>=2.37.0",
    "pyarrow>=19.0.1",
    "shiny>=1.3.0",
    "tenacity>=9.0.0",
    "thefuzz>=0.22.1",
    "zstandard>=0.23.0",
    "pbpstats (>=1.3.11,<2.0.0)",
    "nba-api (>=1.7,<2.0)",
    "sportypy (>=1.0.0,<2.0.0)",
    "sportsdataverse>=0.0.39",
    "plotly>=6.0.0",
    "great-tables>=0.16.1",
    "seaborn>=0.13.2",
    "kaleido==0.2.1",
    "plotnine[extra]>=0.14.5",
    "scikit-learn-intelex>=2025.2.0",
    "pyjson5>=1.6.8",
    "numba>=0.61.0",
    "catboost>=1.2.7",
    "pymc>=5.21.1",
    "duckdb>=1.2.1",
    "tabulate>=0.9.0",
    "sklearn-evaluation>=0.12.2",
    "scikit-learn>=1.6.1",
    "rpy2>=3.6.0.dev2",
    "ipykernel>=6.29.5",
    "ipympl>=0.9.7",
    "notebook>=7.3.3",
    "jupyterthemes>=0.20.0",
]

[project.optional-dependencies]
formatting = [
    "black>=25.1.0",
    "blacken-docs>=1.19.1",
    "isort>=6.0.1",
    "nbconvert>=7.16.6",
    "nbqa>=1.9.1",
]
visualization = [
    "cairosvg>=2.7.1",
    "chart-studio>=1.1.0",
    "colormaps>=0.4.2",
    "imgkit>=1.2.3",
    "lets-plot>=4.6.1",
]
web = [
    "html5lib>=1.1",
    "lxml>=5.3.1",
    "selenium>=4.29.0",
]
extra = [
    "atproto>=0.0.59",
    "atprototools>=0.0.17",
    "memory-profiler>=0.61.0",
    "pyqt6>=6.8.1",
]
ml = [
    "opencv-python>=4.11.0.86",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
