# Code plotting NBA Histograms
```{r}
library(tidyverse)
library(nbastatR)
library(hrbrthemes)
library(ggridges)
library(patchwork)
library(ggtext)
library(ggfx)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 50)

# custom ggplot2 theme
theme_sravan <- theme_minimal(base_size = 9, base_family = "Tahoma") +
  theme(
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "ghostwhite", color = "ghostwhite"),
    plot.title.position = "plot",
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 20),
    plot.margin = margin(10, 10, 15, 10),
    axis.text.x = element_text(size = 10, face = "bold", color = "black"),
    axis.text.y = element_text(size = 10, face = "bold", color = "black"),
    axis.title.x = element_text(size = 12, face = "bold", colour = "black"),
    axis.title.y = element_text(size = 12, face = "bold", colour = "black")
  )

tms <- nba_teams()
# tms <- tms %>% filter(isNonNBATeam == 0)
tms <- tms %>%
  select(slugTeam, nameTeam, idDivision, idConference, colorsTeam, urlThumbnailTeam)
tms$colorsTeam <- gsub(",.*", "", tms$colorsTeam)
```
```{r}
mean(data["agePlayer"])
```
# Load Data
```{r}
df1 <- teams_players_stats(seasons = 2025, types = c("player"), tables = c("general"), modes = c("PerGame"))
df2 <- df1$dataTable
data <- as.data.frame(df2)
```
# Add Team Information
```{r}
data <- left_join(data, tms, by = "slugTeam")
```
# Plot Histogram: Player Age
```{r}
p <- ggplot(data, aes(x = agePlayer)) +
  geom_histogram(binwidth = 1, fill = "#69b3a2", color = "#e9ecef", alpha = 0.9) +
  geom_vline(aes(xintercept = mean(agePlayer))) +
  annotate("text", x = 27, y = 40, label = "Mean Age", angle = 0) +
  theme_sravan +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(face = "bold", size = 20),
    plot.margin = margin(10, 10, 15, 10)
  ) +
  theme(
    axis.text.x = element_text(size = 10, face = "bold", color = "black"),
    axis.text.y = element_text(size = 10, face = "bold", color = "black"),
    axis.title.x = element_text(size = 12, face = "bold", colour = "black"),
    axis.title.y = element_text(size = 12, face = "bold", colour = "black")
  ) +
  labs(
    title = "Histogram of Player Age in the NBA",
    x = "Player Age",
    y = "Number of Players"
  )
ggsave("./figs/R/Player_Age_Histogram.png", p, w = 8, h = 5, dpi = 600)
p
```
# Plot Density Ridges: Player Age
```{r}
data1 <- data %>% filter(idConference == 1)
p1 <- ggplot(data1, aes(x = agePlayer, y = slugTeam, weight = minutes, fill = colorsTeam)) +
  geom_density_ridges(
    # aes(height = ..density..), alpha = 0.5, stat = "density") +
  alpha = 0.5, from = 18, to = 40, quantile_lines = TRUE, quantiles = 2) +
  scale_color_identity(aesthetics = c("fill")) +
  scale_x_continuous(limits = c(18, 40), expand = c(0, 0)) +
  coord_cartesian(clip = "off") +
  theme_sravan +
  labs(x = "Player Age", y = "Team")

data2 <- data %>% filter(idConference == 2)
p2 <- ggplot(data2, aes(x = agePlayer, y = slugTeam, weight = minutes, fill = colorsTeam)) +
  geom_density_ridges(
    # aes(height = ..density..), alpha = 0.5, stat = "density") +
  alpha = 0.5, from = 18, to = 40, quantile_lines = TRUE, quantiles = 2) +
  scale_color_identity(aesthetics = c("fill")) +
  scale_x_continuous(limits = c(18, 40), expand = c(0, 0)) +
  coord_cartesian(clip = "off") +
  theme_sravan +
  theme(axis.title.y = element_blank()) +
  labs(x = "Player Age")
p <- p1 + p2
p <- p +
  plot_annotation(
    title = "Age Distribution of NBA Teams 2024-25",
    subtitle = "Ages are weighted by mins played per game | These are density plots (similar to Histograms)",
    caption = "@sradjoker.bsky.social | x:@sradjoker | Source: nba.com/stats",
    theme = theme(
      plot.title = element_markdown(face = "bold", family = "Tahoma", size = 20),
      plot.subtitle = element_text(family = "Tahoma", size = 12),
      plot.background = element_rect(fill = "ghostwhite", color = "ghostwhite"),
      plot.caption = element_text(family = "Tahoma", size = 12)
    )
  )

ggsave("./figs/R/Player_Age_Ridge_1.png", p, w = 8, h = 10, dpi = 600)
```

# Plot Histogram: Player Age
```{r}
p <- ggplot(data, aes(x = ast)) +
  geom_density( fill = "#69b3a2", color = "#e9ecef", alpha = 0.9) +
  theme_sravan +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(face = "bold", size = 20),
    plot.margin = margin(10, 10, 15, 10)
  ) +
  theme(
    axis.text.x = element_text(size = 10, face = "bold", color = "black"),
    axis.text.y = element_text(size = 10, face = "bold", color = "black"),
    axis.title.x = element_text(size = 12, face = "bold", colour = "black"),
    axis.title.y = element_text(size = 12, face = "bold", colour = "black")
  ) 
  # labs(
  #   title = "Histogram of Player Age in the NBA",
  #   x = "Player Age",
  #   y = "Number of Players"
  # )
ggsave("./figs/R/Player_Histogram.png", p, w = 8, h = 5, dpi = 600)
p
```